# * ------------------------------------------------------------------
# * Organization   : Barcelona Supercomputing Center
# * File           : axi_to_pmesh_bridge_lint_waiver.tcl
# * Description    : lint waivers for the axi_to_pmesh_bridge.
# * ------------------------------------------------------------------
# * COPYRIGHT
# *  Copyright (c) Barcelona Supercomputing Center, 2024-2025.
# * ------------------------------------------------------------------
# * LICENSE
# *  Licensed under the Solderpad Hardware License v 2.1 (the
# *  "License"); you may not use this file except in compliance
# *  with the License, or, at your option, the Apache License
# *  version 2.0. You may obtain a copy of the License at
# *
# *  http://www.solderpad.org/licenses/SHL-2.1
# *
# *  Unless required by applicable law or agreed to in writing,
# *  work distributed under the License is distributed on an
# *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# *  either express or implied. See the License for the specific
# *  language governing permissions and limitations under the License.
# * ------------------------------------------------------------------
# * Revision History
# *  Revision   | Author                                | Description
# *  0.0.1      | Abbas Haghi - abbas.haghi@bsc.es      | initial version
# *             | Manjunath - manjunath.kalmath@bsc.es  | initial version
# *             | lap - luis.plana@bsc.es               | initial version
# * ------------------------------------------------------------------
# * NOTES:
# * - waivers target Synopsys vc_static.
# * - tested with Version V-2023.12 for linux64 - Nov 24, 2024
# * ------------------------------------------------------------------
waive_violation -add AXI_PMESH_PKG_1  -app Lint -status Waived -tag "W528"                     -filter { (FileName =~ "axi_to_pmesh_bridge_pkg.sv")        AND Statement =~ ".*len.*"                    }  -ignore -regex -comment {"a subset of bits not used in module"}

waive_violation -add AXI_PMESH_AD_1   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "addr_to_x_y.sv")                    AND Statement =~ ".*axi2noc_req_address_s0.*" }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_AD_2   -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "addr_to_x_y.sv")                    AND Statement =~ ".*axi2noc_req_address_s0.*" }  -ignore -regex -comment {"a subset of bits not used in module"}

waive_violation -add AXI_PMESH_AE_1   -app Lint -status Waived -tag "UndrivenNUnloaded-ML"     -filter { (FileName =~ "alexforencich_priority_encoder.v")  AND Statement =~ ".*stage_valid.*"            }  -ignore -regex -comment {"unused signal in external module"}
waive_violation -add AXI_PMESH_AE_2   -app Lint -status Waived -tag "UndrivenNUnloaded-ML"     -filter { (FileName =~ "alexforencich_priority_encoder.v")  AND Statement =~ ".*stage_enc.*"              }  -ignore -regex -comment {"unused signal in external module"}
waive_violation -add AXI_PMESH_AE_3   -app Lint -status Waived -tag "W120"                     -filter { (FileName =~ "alexforencich_priority_encoder.v")  AND Statement =~ ".*stage_valid.*"            }  -ignore -regex -comment {"unused signal in external module"}
waive_violation -add AXI_PMESH_AE_4   -app Lint -status Waived -tag "W120"                     -filter { (FileName =~ "alexforencich_priority_encoder.v")  AND Statement =~ ".*stage_enc.*"              }  -ignore -regex -comment {"unused signal in external module"}
waive_violation -add AXI_PMESH_AE_5   -app Lint -status Waived -tag "W123"                     -filter { (FileName =~ "alexforencich_priority_encoder.v")  AND Statement =~ ".*stage_valid.*"            }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_AE_6   -app Lint -status Waived -tag "W123"                     -filter { (FileName =~ "alexforencich_priority_encoder.v")  AND Statement =~ ".*stage_enc.*"              }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_AE_7   -app Lint -status Waived -tag "W486"                     -filter { (FileName =~ "alexforencich_priority_encoder.v")  AND Statement =~ ".*output_unencoded.*"       }  -ignore -regex -comment {"ignore carry in addition"}

waive_violation -add AXI_PMESH_SR_1   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARCACHE.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_2   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARQOS.*"            }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_3   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARUSER.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_4   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARPROT.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_5   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARLOCK.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_6   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARBURST.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_7   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARREGION.*"         }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_8   -app Lint -status Waived -tag "STARC05-2.11.3.1"         -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*state.*"                  }  -ignore -regex -comment {"it is done intentionally"}
waive_violation -add AXI_PMESH_SR_9   -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARCACHE.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_10  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARQOS.*"            }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_11  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARUSER.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_12  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARPROT.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_13  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARLOCK.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_14  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARBURST.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_15  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*S_AXI_ARREGION.*"         }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SR_16  -app Lint -status Waived -tag "W287b"                    -filter { (FileName =~ "axi_slave_rd_pipeline.sv")          AND Statement =~ ".*usage_o.*"                }  -ignore -regex -comment {"unused port in external module"}

waive_violation -add AXI_PMESH_SW_1   -app Lint -status Waived -tag "ImproperRangeIndex-ML"    -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_bvalid.*"               }  -ignore -regex -comment {"range is known to be correct"}
waive_violation -add AXI_PMESH_SW_2   -app Lint -status Waived -tag "ImproperRangeIndex-ML"    -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_wid.*"                  }  -ignore -regex -comment {"range is known to be correct"}
waive_violation -add AXI_PMESH_SW_3   -app Lint -status Waived -tag "ImproperRangeIndex-ML"    -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_noc_ack_cnt.*"          }  -ignore -regex -comment {"range is known to be correct"}
waive_violation -add AXI_PMESH_SW_4   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWCACHE.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_5   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWQOS.*"            }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_6   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWUSER.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_7   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_WUSER.*"            }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_8   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWPROT.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_9   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWLOCK.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_10  -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWBURST.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_11  -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWREGION.*"         }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_12  -app Lint -status Waived -tag "UnloadedNet-ML"           -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_mask_1.*"               }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_SW_13  -app Lint -status Waived -tag "STARC05-2.11.3.1"         -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*state.*"                  }  -ignore -regex -comment {"it is done intentionally"}
waive_violation -add AXI_PMESH_SW_14  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_mask_1.*"               }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_15  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_wr_ack_id.*"            }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_16  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_wr_rq_id.*"             }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_17  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_upper_limit_N.*"        }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_18  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_bvalid_id.*"            }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_19  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_addr_N.*"               }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_20  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_addr_aligned.*"         }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_21  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_N.*"                    }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_SW_22  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWCACHE.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_23  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWQOS.*"            }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_24  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWUSER.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_25  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_WUSER.*"            }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_26  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWPROT.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_27  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWLOCK.*"           }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_28  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWBURST.*"          }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_29  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_AWREGION.*"         }  -ignore -regex -comment {"unsupported AXI bus signal"}
waive_violation -add AXI_PMESH_SW_30  -app Lint -status Waived -tag "UnloadedNet-ML"           -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_lower_limit.*"          }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_SW_31  -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*S_AXI_BID.*"              }  -ignore -regex -comment {"multiple assignments are correct"}
waive_violation -add AXI_PMESH_SW_32  -app Lint -status Waived -tag "W486"                     -filter { (FileName =~ "axi_slave_wr_pipeline.sv")          AND Statement =~ ".*s_size.*"                 }  -ignore -regex -comment {"ignore carry in addition"}

waive_violation -add AXI_PMESH_AP_1   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "axi_to_pmesh_bridge.sv")            AND Statement =~ ".*CACHE_LINE_BITS.*"        }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_AP_2   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "axi_to_pmesh_bridge.sv")            AND Statement =~ ".*ATOMIC_TRF_BITS_MAX.*"    }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_AP_3   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "axi_to_pmesh_bridge.sv")            AND Statement =~ ".*NC_STORE_BITS_MAX.*"      }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_AP_4   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "axi_to_pmesh_bridge.sv")            AND Statement =~ ".*IN_FLIGHT_MAX.*"          }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_AP_5   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "axi_to_pmesh_bridge.sv")            AND Statement =~ ".*wake_up_cnt_d.*"          }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_AP_6   -app Lint -status Waived -tag "W287b"                    -filter { (FileName =~ "axi_to_pmesh_bridge.sv")            AND Statement =~ ".*usage_o.*"                }  -ignore -regex -comment {"unused port in external module"}

waive_violation -add AXI_PMESH_F3_1   -app Lint -status Waived -tag "ConstName"                -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*dtype.*"                  }  -ignore -regex -comment {"external file uses different naming convention"}
waive_violation -add AXI_PMESH_F3_2   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*write_pointer_n.*"        }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_F3_3   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*read_pointer_n.*"         }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_F3_4   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*status_cnt_n.*"           }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_F3_5   -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*testmode_i.*"             }  -ignore -regex -comment {"unused port in external module"}
waive_violation -add AXI_PMESH_F3_6   -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*status_cnt_n.*"           }  -ignore -regex -comment {"multiple assignment in external module"}
waive_violation -add AXI_PMESH_F3_7   -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*read_pointer_n.*"         }  -ignore -regex -comment {"multiple assignment in external module"}
waive_violation -add AXI_PMESH_F3_8   -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*write_pointer_n.*"        }  -ignore -regex -comment {"multiple assignment in external module"}
waive_violation -add AXI_PMESH_F3_9   -app Lint -status Waived -tag "STARC05-1.3.1.3"          -filter { (FileName =~ "fifo_v3.sv")                        AND Statement =~ ".*~rst_ni.*"                }  -ignore -regex -comment {"signal used in external module"}

waive_violation -add AXI_PMESH_NQ_1   -app Lint -status Waived -tag "W175"                     -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*FLITS_PER_MSG.*"          }  -ignore -regex -comment {"used in parameter/typedef declaration"}
waive_violation -add AXI_PMESH_NQ_2   -app Lint -status Waived -tag "W175"                     -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*MESSAGE_BITS.*"           }  -ignore -regex -comment {"used in parameter/typedef declaration"}
waive_violation -add AXI_PMESH_NQ_3   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*msg_addr_t.*"             }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_NQ_4   -app Lint -status Waived -tag "ImproperRangeIndex-ML"    -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*message.*"                }  -ignore -regex -comment {"range is known to be correct"}
waive_violation -add AXI_PMESH_NQ_5   -app Lint -status Waived -tag "ImproperRangeIndex-ML"    -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*unrolled_req.*"           }  -ignore -regex -comment {"range is known to be correct"}
waive_violation -add AXI_PMESH_NQ_6   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*unrolled_req.*"           }  -ignore -regex -comment {"a subset of unrolled_req.data not used"}
waive_violation -add AXI_PMESH_NQ_7   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*flit_cnt.*"               }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_NQ_8   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*msg_len.*"                }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_NQ_9   -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*hdr1.*"                   }  -ignore -regex -comment {"multiple assignments are correct"}
waive_violation -add AXI_PMESH_NQ_10  -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*hdr2.*"                   }  -ignore -regex -comment {"multiple assignments are correct"}
waive_violation -add AXI_PMESH_NQ_11  -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*hdr3.*"                   }  -ignore -regex -comment {"multiple assignments are correct"}
waive_violation -add AXI_PMESH_NQ_12  -app Lint -status Waived -tag "W528"                     -filter { (FileName =~ "noc_requests.sv")                   AND Statement =~ ".*wide_data.*"              }  -ignore -regex -comment {"a subset of bits not used in module"}

waive_violation -add AXI_PMESH_NR_1   -app Lint -status Waived -tag "UnloadedNet-ML"           -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*rsp_type.*"               }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_NR_2   -app Lint -status Waived -tag "UnloadedNet-ML"           -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*mshr_tag.*"               }  -ignore -regex -comment {"a subset of mshr_tag.mrid not used"}
waive_violation -add AXI_PMESH_NR_3   -app Lint -status Waived -tag "UnloadedNet-ML"           -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*noc2_data_in_first.*"     }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_NR_4   -app Lint -status Waived -tag "W528"                     -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*rsp_type.*"               }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_NR_5   -app Lint -status Waived -tag "W528"                     -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*noc2_data_in_first.*"     }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_NR_6   -app Lint -status Waived -tag "W528"                     -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*hdr1.*"                   }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_NR_7   -app Lint -status Waived -tag "W528"                     -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*message.*"                }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_NR_8   -app Lint -status Waived -tag "W528"                     -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*mrid.*"                   }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_NR_9   -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "noc_responses.sv")                  AND Statement =~ ".*clk.*"                    }  -ignore -regex -comment {"module can be combinatorial for some parameter values"}

waive_violation -add AXI_PMESH_TU_1   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*unrolled_rsp.*"           }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_TU_2   -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*unrolled_rsp.*"           }  -ignore -regex -comment {"a subset of bits not used in module"}
waive_violation -add AXI_PMESH_TU_3   -app Lint -status Waived -tag "W175"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*MR_MAX_REQS_BITS.*"       }  -ignore -regex -comment {"used in parameter/typedef declaration"}
waive_violation -add AXI_PMESH_TU_4   -app Lint -status Waived -tag "W175"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*WR_PART_NUM_BITS.*"       }  -ignore -regex -comment {"used in parameter/typedef declaration"}
waive_violation -add AXI_PMESH_TU_5   -app Lint -status Waived -tag "W175"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*BRIDGE_IN_FLIGHT_BITS.*"  }  -ignore -regex -comment {"used in parameter/typedef declaration"}
waive_violation -add AXI_PMESH_TU_6   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*in_flt_cnt.*"             }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_7   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*in_flt_tail.*"            }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_8   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*in_flt_head.*"            }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_9   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*wr_part_cnt.*"            }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_10  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*wr_part_addr.*"           }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_11  -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*wr_mr_inflt_cnt.*"        }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_12  -app Lint -status Waived -tag "W287b"                    -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*usage_o.*"                }  -ignore -regex -comment {"unused port in external module"}
waive_violation -add AXI_PMESH_TU_13  -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*aif_wr_trans_data.*"      }  -ignore -regex -comment {"port present only with non-default parameter values"}
waive_violation -add AXI_PMESH_TU_14  -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*aif_rd_addr_data.*"       }  -ignore -regex -comment {"port present only with non-default parameter values"}
waive_violation -add AXI_PMESH_TU_15  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*aif_wr_trans_data.*"      }  -ignore -regex -comment {"port present only with non-default parameter values"}
waive_violation -add AXI_PMESH_TU_16  -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*aif_rd_addr_data.*"       }  -ignore -regex -comment {"port present only with non-default parameter values"}
waive_violation -add AXI_PMESH_TU_17  -app Lint -status Waived -tag "W415a"                    -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*in_flt_issd.*"            }  -ignore -regex -comment {"multiple assignments are correct"}
waive_violation -add AXI_PMESH_TU_18  -app Lint -status Waived -tag "W486"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*req_size_rd.*"            }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_19  -app Lint -status Waived -tag "W486"                     -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*req_size_wr.*"            }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_TU_20  -app Lint -status Waived -tag "W287b"                    -filter { (FileName =~ "transfer_unroller.sv")              AND Statement =~ ".*full_o.*"                 }  -ignore -regex -comment {"unused port in external module"}

waive_violation -add AXI_PMESH_WU_1   -app Lint -status Waived -tag "UnloadedInPort-ML"        -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*wr_trans.*"               }  -ignore -regex -comment {"structure field not used in module"}
waive_violation -add AXI_PMESH_WU_2   -app Lint -status Waived -tag "W240"                     -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*wr_trans.*"               }  -ignore -regex -comment {"structure field not used in module"}
waive_violation -add AXI_PMESH_WU_3   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*AXI_DATA_WIDTH.*"         }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_WU_4   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*NUM_SEC.*"                }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_WU_5   -app Lint -status Waived -tag "AlwaysFalseTrueCond-ML"   -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*SEC_BITS.*"               }  -ignore -regex -comment {"parameter validation - depends on value"}
waive_violation -add AXI_PMESH_WU_6   -app Lint -status Waived -tag "W175"                     -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*SEC_CNT_BITS.*"           }  -ignore -regex -comment {"used in parameter/typedef declaration"}
waive_violation -add AXI_PMESH_WU_7   -app Lint -status Waived -tag "ImproperRangeIndex-ML"    -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*wr_trans.data.*"          }  -ignore -regex -comment {"range is known to be correct"}
waive_violation -add AXI_PMESH_WU_8   -app Lint -status Waived -tag "ImproperRangeIndex-ML"    -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*wr_trans.wstrb.*"         }  -ignore -regex -comment {"range is known to be correct"}
waive_violation -add AXI_PMESH_WU_9   -app Lint -status Waived -tag "W164a_b"                  -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*mr_id.*"                  }  -ignore -regex -comment {"ignore carry in addition"}
waive_violation -add AXI_PMESH_WU_10  -app Lint -status Waived -tag "W287b"                    -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*output_valid.*"           }  -ignore -regex -comment {"unused port in external module"}
waive_violation -add AXI_PMESH_WU_11  -app Lint -status Waived -tag "W287b"                    -filter { (FileName =~ "write_unroller.sv")                 AND Statement =~ ".*output_unencoded.*"       }  -ignore -regex -comment {"unused port in external module"}
